### ISSUE TITLE
Add TCP check to service registration

### ISSUE THREAD

**Issue by kkirsche** [gmr/consulate#101]
From https://www.consul.io/api/agent/check.html#register-check

TCP (string: "") - Specifies a TCP to connect against the value of TCP (expected to be an IP or hostname plus port combination) every Interval. If the connection attempt is successful, the check is passing. If the connection attempt is unsuccessful, the check is critical. In the case of a hostname that resolves to both IPv4 and IPv6 addresses, an attempt will be made to both addresses, and the first successful connection attempt will result in a successful check.

**Comment by gmr** [comment]
This has been added. 1.0 should be released within the next week or two, barring any issues.
