### ISSUE TITLE
'ls' subcommand for KV

### ISSUE THREAD

**Issue by xakraz** [gmr/consulate#16]
It could be great to have a 'ls' subcommand to the KV store.

Is there any plan to implement a behavior like https://github.com/coreos/etcdctl ?

**Comment by gmr** [comment]
I agree, I'll look to add it. I'm going to be adding ``mv`` and ``cp`` as well.

**Comment by gmr** [comment]
The first implementation of this will only list all keys instead of treating it how ``ls`` would normally work but will drop with 0.4.0 which I am pushing soon.
