### ISSUE TITLE
Allow specifying an explicit address for service registration

### ISSUE THREAD

**Issue by ctheune** [gmr/consulate#26]
According to the Docs of the HTTP API it's possible to register a custom address for a service - the default only uses the Agent's address. This is insufficent for many use cases.

I'm trying to prepare a pull request in a minute.

**Comment by ctheune** [comment]
Sorry, too little exercise in git (as I'm a Mercurial guy).

The change is quite trivial:

add the address here:

    def register(self, name, address=None, service_id=None, port=None, ...

and here:

    payload = {'id': service_id, ...
        'address': address,

That's it.

**Comment by gmr** [comment]
Thanks for the report. Added and will be released with 0.4.0.

**Comment by ctheune** [comment]
Yay!
