### ISSUE TITLE
kv restore removes double quotes from values

### ISSUE THREAD

**Issue by piavlo** [gmr/consulate#28]
Then using consulate kv restore from previous consulate kv backup, the values which had double quotes are inserted with quotes  removed, so that if i had a `"somevalue"` or would become `somevalue` after restore.

**Comment by piavlo** [comment]
@gmr  The problem is solved by commenting json parsing of row['Value']
https://github.com/gmr/consulate/blob/master/consulate/api/base.py#L134
Why do we need to double json parse both respnse body and Value withing body too?

**Comment by ctheune** [comment]
Well, the consul API itself is json. The value is completely opaque to consul and may contain whatever. It typically is base64 encoded (see a few lines before) and could be anything. If you store json as your data then you are one level deeper (like with inception) and have to do the encoding/decoding again.

I'm just surprised that this isn't an explicit flag but sniffed. Not really happy about that.

**Comment by gmr** [comment]
In master, the attempt to json decode a key's value has been removed. 0.5.0 will be released with this behavior soon.

**Comment by gmr** [comment]
0.5.0 is released and this should be good to go. Pls reopen if you have any additional issues.
