### ISSUE TITLE
Add timeout option for api request

### ISSUE THREAD

**Issue by fizyk** [gmr/consulate#30]
It's missing, and in order to add timeout to all possible gets within adapters, One actually have to overwrite whole adapter.

**Comment by ckauhaus** [comment]
I wonder if this is the right approach. We have the requirement to accept self-signed https certs, so I'm currently monkey-patching the adapters.Request class.

Would it not be better to have the Consul.__init__ constructor accept a custom adapter object (similar to the low-level API classes)? This would allow advanced users to customize whichever aspect of connection behaviour they need.

**Comment by gmr** [comment]
@ckauhaus without looking at either PR, that was my thought as to the direction.

**Comment by fizyk** [comment]
Sure, I have to admit that its' a rough draft.

But shouldn't default adapter also have some timeout option rather than hang forever if something goes wrong with consul it tries to connect to? There should be both option to extend adapter and simply set timeout event though I might simply not see other possibility than timeouts.

The api.* objects seems to be rather coupled to api.Response object most of the time. and apart from that there's only requests used in adapter itself at the moment.

**Comment by fizyk** [comment]
@gmr, @ckauhaus could you take a look at the PR again?

**Comment by gmr** [comment]
Merged the PR.

**Comment by ckauhaus** [comment]
looks good
