### ISSUE TITLE
Unicode decode problem under Python3

### ISSUE THREAD

**Issue by ckauhaus** [gmr/consulate#32]
Currently, the dependency to simplejson is optional in consulate. When running under Python3 *without* simplejson installed, consulate fails to decode the response properly and returns an indigested bytestring.

Example without simplejson installed:
```
>>> c = consulate.Consul()
>>> c.catalog.datacenters()
b'["services","test"]'
```

Example with simplejson installed:
```
>>> c = consulate.Consul()
>>> c.catalog.datacenters()
['services', 'test']
```

Return values from other operations differ accordingly.

I see basically two options to fix it: either decode the HTTP response body explicitely or make simplejson an explicit dependency.

**Comment by arturhoo** [comment]
Agreed @ckauhaus, right now, `consulate` is not python 3 compatible unless simplejson is installed. Fetching keys from Consul's KV storage is also not possible:

```
```

**Comment by gmr** [comment]
This should now be fixed in master.

**Comment by gmr** [comment]
(if you can test that it works to your expectations, that'd be great!)

**Comment by ckauhaus** [comment]
Works. :-)

**Comment by gmr** [comment]
0.5.0 is released and this should be good to go. Pls reopen if you have any additional issues.
