### ISSUE TITLE
Documentation out of sync with production-ready library

### ISSUE THREAD

**Issue by inhumantsar** [gmr/consulate#34]
I'm able to connect, set and read kv pairs from Consul with consulate without too much trouble. `set_record()` throws a fit whenever I try to use `replace=False`. As you can see by the `func_code` line, set_record only shows the self, item, flags and value params. I'm running 0.4.0 on Python 2.7.6 and have never had an older version of consulate on this box.

    >>> key='moo/too'
    >>> value='foobar'
    >>> s.kv.set_record(item=key, value=value, replace=False)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: set_record() got an unexpected keyword argument 'replace'
    >>> print s.kv.set_record
    <bound method KV.set_record of <consulate.api.kv.KV object at 0x10527e7d0>>
    >>> print s.kv.set_record.func_code.co_varnames
    ('self', 'item', 'flags', 'value')
    >>> print s.kv.set(key,value)
    None
    >>> print s.kv.get(key)
    foobar
    >>> print s.kv.delete(key)
    <consulate.api.base.Response object at 0x105288d50>
    >>> print s.kv.get(key)
    None
    >>> print s.kv.set_record(item=key,value=value)
    None
    >>> print s.kv.get(key)
    foobar
    
    $ pip show consulate
    ---
    Metadata-Version: 2.0
    Name: consulate
    Version: 0.4.0
    Summary: A Client library for the Consul
    Home-page: https://consulate.readthedocs.org
    Author: Gavin M. Roy
    Author-email: gavinr@aweber.com
    License: BSD
    Location: /Library/Python/2.7/site-packages
    Requires: requests
    
    $ python --version
    Python 2.7.6
    
    $ uname -a
    Darwin martins.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
    
    $ sw_vers -productVersion
    10.10.3

**Comment by inhumantsar** [comment]
So it appears that readthedoc's "latest" != "latest stable" (ie 0.4.0) but rather, the master branch where development is happening. This runs counter to expected behaviour. Take the *boto* project for example. They use "latest" on RTD to display documentation for the version that is "latest" in the pip repos, which is what the vast majority of people will be looking for. 

This isn't a bug in the library itself so I'm going to change the title to match. 

New request: It would be helpful to have the docs display the version they're referencing, though defaulting to "latest stable" rather than the development branch would make the most sense.

**Comment by gmr** [comment]
Bummer, that's annoying. I'll update RTD.

**Comment by gmr** [comment]
Updated to use "stable" in RTD which is pointing to 0.4.0 at the time of this comment. Sorry for the trouble.
