### ISSUE TITLE
Service registration print spurious error message

### ISSUE THREAD

**Issue by ckauhaus** [gmr/consulate#37]
When issuing an API call that returns nothing (as expected), consulate prints a spurious error message to stdout:

```
>>> c.agent.service.register('myservice', address='myaddr')
('Error:', ValueError('No JSON object could be decoded',))
True
```

The HTTP call just exits with status 200 and returns no body. This is ok by Consul's specs. So I'd suggest just to remove the print() statement in api/base.py.

**Comment by gmr** [comment]
Bah, it shouldn't have been there anyway.

**Comment by gmr** [comment]
I'll do a rev bump today to pypi.

**Comment by ctheune** [comment]
I think this didn't go into the 0.5.1. release ... any chance for 0.5.2 in the near future? I was still getting confused by this today :)
