### ISSUE TITLE
status.peers() returns string instead of list if only one peer exists

### ISSUE THREAD

**Issue by ctheune** [gmr/consulate#39]
Hi,

I'm currently running some code against a test installation of consul in a single-node vagrant environment. I stumbled over the issue that peers() will return a single string instead of a list in this case:

(Pdb) p connection.status.peers()
2015-05-19 11:03:38,533 INFO  [requests.packages.urllib3.connectionpool][Dummy-4] Starting new HTTP connection (1): consul-ext.service.services.vgr.consul.local
u'10.0.2.15:8300'

**Comment by gmr** [comment]
Fixed in master, will release a new version soon.

**Comment by ctheune** [comment]
Awesome, thanks. Sorry for not providing a patch myself - was quite busy yesterday. :)
