### ISSUE TITLE
consulate urllib3.connection dependency broken

### ISSUE THREAD

**Issue by rupskygill** [gmr/consulate#42]
On Ubuntu 14.04.2 LTS, consulate fails as its dependency on urllib3.connection no longer exists. 

sbapp@ppop-repo:~$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import consulate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/consulate/__init__.py", line 24, in <module>
    from consulate import adapters
  File "/usr/local/lib/python2.7/dist-packages/consulate/adapters.py", line 9, in <module>
    import requests_unixsocket
  File "/usr/local/lib/python2.7/dist-packages/requests_unixsocket/__init__.py", line 4, in <module>
    from .adapters import UnixAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests_unixsocket/adapters.py", line 9, in <module>
    from urllib3.connection import HTTPConnection
ImportError: No module named connection
>>>

sbapp@ppop-repo:~$ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

sbapp@ppop-repo:~$ pip freeze
argparse==1.2.1
chardet==2.0.1
colorama==0.2.5
consulate==0.5.1
html5lib==0.999
meld3==0.6.10
requests==2.2.1
requests-unixsocket==0.1.4
six==1.5.2
ssh-import-id==3.21
supervisor==3.0b2
urllib3==1.7.1
wheel==0.24.0
wsgiref==0.1.2

**Comment by rupskygill** [comment]
Found a fix. On Ubuntu 14.04 LTS need to upgrade the requests package from 2.2.1 to version 2.70. However requests upgrade breaks ubuntu's pip. Hence fix also involves install pip via easy_install. Below worked for me:

$ sudo apt-get purge python-pip python-requests 
$ sudo easy_install -U pip
$ /usr/local/bin/pip install --upgrade requests consulate

$ /usr/local/bin/pip freeze | grep -i requests
requests==2.7.0
requests-unixsocket==0.1.4

**Comment by gmr** [comment]
Yuck, sorry about that -- is a bit lower level than the library. I generally just do easy_install on Ubuntu to install pip and don't do other Ubuntu packages for things on pypi. I know that doesn't work for everyone.

**Comment by sheldonh** [comment]
Is there a workaround available that has pip install consulate work on Ubuntu?
