### ISSUE TITLE
consulate kv backup replaces "" with null

### ISSUE THREAD

**Issue by rhelmer** [gmr/consulate#51]
If I have a key in consul with a value of "" (empty string), a `consulate kv backup` will dump that with `null` instead.

**Comment by gmr** [comment]
Unfortunately, this is not an issue with consulate. Consul returns a ``null`` in the JSON reply for a key with an empty value in it. I replicated this by setting an empty string in consulate and via the Consul web-ui.

**Comment by zirpu** [comment]
Just adding an example script for an example of how to backup if you want [None, "null"] -> ""
```python
#!/usr/bin/env python

from __future__ import print_function
import consulate
import json

session = consulate.Session()
records = []
for r in session.kv.records():
    if r[-1] in [None, "null"]:  # our convention is None => ""
        t = list(r)
        t[-1] = ""
        r = t
    records.append(r)
print(json.dumps(records, indent=True, sort_keys=True))
```
