### ISSUE TITLE
Allow `consulate kv get` to return recursive listing of keys?

### ISSUE THREAD

**Issue by MWers** [gmr/consulate#56]
What do you think about adding a `-r` option to `consulate kv get` to request all keys in a given path? Like this:

```
$ consulate kv get test/recursive/one
1

$ consulate kv get test/recursive/two
2

$ consulate kv get test/recursive/three
3

$ consulate kv get test/recursive
None

$ consulate kv get -r test/recursive
test/recursive/one   1
test/recursive/two   2
test/recursive/three 3
```

I'd be happy to add it to the CLI and submit a pull request, just wanted to make sure that it's a welcome contribution.

**Comment by gmr** [comment]
Sounds great :)

**Comment by MWers** [comment]
Cool!

Quick question... This is what I've implemented:

```
$ consulate kv get -r test/recursive/
test/recursive/KEY_1	one
test/recursive/KEY_2	two
test/recursive/KEY_3	three
```

It would be nice to offer an option similar to `envconsul` where the prefix is trimmed from the resulting keys, like this:

```
$ consulate kv get -r test/recursive/
KEY_1	one
KEY_2	two
KEY_3	three
```

Or with a shorter prefix, like this:

```
$ consulate kv get -r test/
recursive/KEY_1	one
recursive/KEY_2	two
recursive/KEY_3	three
```

Do you think that this should be the default? Or should we offer a flag, like `-t, --trim`, to trim the prefix from the output?

Thanks!

**Comment by gmr** [comment]
I do not think it should be the default, and --trim # would be good where # defaults to 1.

**Comment by MWers** [comment]
What would the number in `--trim #` do? Trim one level of prefix? I was thinking that `--trim` wouldn't take a number but it would signify that we should subtract the full prefix given to the cli from the key returned, like this:

```
# full keys:
# test/recursive/KEY_1
# test/recursive/KEY_2
# test/recursive/KEY_3

# default output:
$ consulate kv get -r test/recursive/
test/recursive/KEY_1    one
test/recursive/KEY_2    two
test/recursive/KEY_3    three

# trimmed output:
$ consulate kv get -r --trim test/recursive/
KEY_1   one
KEY_2   two
KEY_3   three

# trimmed output (shorter prefix specified as arg):
$ consulate kv get -r --trim test/
recursive/KEY_1   one
recursive/KEY_2   two
recursive/KEY_3   three
```

Would this work?

Thanks!

**Comment by gmr** [comment]
Sure.. was just thinking that adding a default # of 1 that could be overridden would allow for

```
$ consulate kv get -r test
test/recursive/KEY_1    one
test/recursive/KEY_2    two
test/recursive/KEY_3    three

$ consulate kv get -r --trim test
recursive/KEY_1   one
recursive/KEY_2   two
recursive/KEY_3   three

$ consulate kv get -r --trim 2 test
KEY_1   one
KEY_2   two
KEY_3   three
```
