### ISSUE TITLE
Support for value in acquire_lock

### ISSUE THREAD

**Issue by rvrignaud** [gmr/consulate#63]
Hello,

It's possible in Consul API to put a lock with a value associated (https://www.consul.io/docs/agent/http/kv.html).
It seems that it's not currently possible with consulate.
Would you mind adding that support ?

**Comment by scalp42** [comment]
@rvrignaud what the value should be ? The result of the command to run for example or a parameter passed?

**Comment by gmr** [comment]
Added, thanks for the suggestion.

**Comment by gmr** [comment]
Closing this due to lack of a response to feedback and now f8d4d7c addresses the feature request. Thanks for the contribution.
