### ISSUE TITLE
ACL update does not create ACL, if ACL does not exist.

### ISSUE THREAD

**Issue by vpack** [gmr/consulate#73]
I confirmed that its not a consul server configuration issue - I am able to use HTTP API update (upsert) for ACL and it works ok.

However when i do the same with Consulate, it does not error out but does not create the ACLs in Consul.

Thanks for looking into this.

**Comment by vpack** [comment]
I should say i get a 'False' return code. 

```
      rc = consul.acl.update(acl_id=acl_id,name=name,acl_type=acl_type,rules=rules)
      if not rc: print("Failed..")
```

Any ideas ?

**Comment by gmr** [comment]
The Consul API documentation specifically states it's an upsert command if the ACL does not exist:

"If the ID does not exist, the ACL will be upserted. In this sense, create and update are identical." from https://www.consul.io/docs/agent/http/acl.html

I don't think I should make the client library behave differently.  Thoughts?

**Comment by vpack** [comment]
Thanks gmr. Yes, I am able to do upserts just fine via curl.

Since it works when i run via curl commands but not via python code, I am not sure if consulate does anything differently.
Is there a debug feature to view the http requests ? That may help understand the reason for failure.

**Comment by gmr** [comment]
I've tested this with the current code and it works. Not sure where the issue was, but 1.0 should be released within the next week or two, barring any issues.
