### ISSUE TITLE
Not possible to set timeout on adapter.Request()

### ISSUE THREAD

**Issue by benagricola** [gmr/consulate#78]
The ability to add a timeout option to the `adapter.Request()` object, in PR #31, was broken by the change made in 7dec13665d5a5827ab34f905f90c067f08212f1c to add Unix Socket support the passed in adapter.

It used to be possible to pass in an instantiated adapter (allowing one to set the timeout in their own code), but now the adapter is always instantiated with no options inside `Consul.__init__()` - regardless of whether it's already an instance of the adapter class itself or not: [relevant code](/gmr/consulate/blob/master/consulate/__init__.py#L68).

Happy to supply a PR for fixing this but not sure what the best fix is - either reverting the change and making it necessary to instantiate any custom adapter passed in, or checking the passed in adapter to work out if it's instantiated or not and then instantiating if necessary.

Thoughts?

**Comment by kkirsche** [comment]
you should be able to do a

c = consulate.Consul()
c._adapter.timeout = 5
