### ISSUE TITLE
How To ...?

### ISSUE THREAD

**Issue by gamename** [gmr/consulate#80]
Hi,

What's the api equivalent of "consul members list"?  I'm trying to write a utility using consulate which starts with a snapshot of all known nodes.

TIA,
-T

**Comment by gmr** [comment]
http://consulate.readthedocs.org/en/stable/catalog.html#consulate.api.catalog.Catalog.nodes

Should be something like:

```python
import consulate

# Create a new instance of a consulate session
session = consulate.Consul()

# Get all of the service checks for the local agent
checks = session.catalog.nodes()
```
