### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by jantman** [gmr/consulate#82]
Are there any plans for a release soon? Specifically, I'm hoping to get one that includes #70 (fix for #68) so I can stop running off of my own fork...

**Comment by strarsis** [comment]
For installing from repository:
````
# pip install git+https://github.com/gmr/consulate.git@master
````

**Comment by jantman** [comment]
@gmr Is this project still alive? It looks like there's quite a bit of interest in a release, not to mention there were a lot of API additions in Consul 0.8.

If you don't have interest in continuing this, is there a chance you'd be willing to give someone else (who's actively using this in production) commit and/or pypi rights to maintain the project?

**Comment by fusiondog** [comment]
You may look at https://github.com/mantl/consul-cli/wiki/KV

**Comment by jantman** [comment]
@fusiondog I appreciate it, but that's not Python. We have *quite a bit* of tooling running in production right now that uses the Python API of consulate (i.e. calling consulate from other Python code), though we're currently running a [branch](https://github.com/jantman/consulate/tree/nullfix) that pulls in @bdclark 's fork mainly for https://github.com/jantman/consulate/commit/886864c

However we have very strong feelings against installing from a git clone, as opposed to installing an official package from PyPI. This is coming up again because we're looking to move to doing backups using Consul's new built-in [snapshot](https://www.consul.io/api/snapshot.html) API, but that's much newer than the last release of this project...

**Comment by gmr** [comment]
1.0 should be released within the next week or two, barring any issues.

**Comment by csawyerYumaed** [comment]
Any update on a 1.0 release? what's blocking? anything I can help with, maybe?
