### ISSUE TITLE
Vault Leader Status Lost after restore

### ISSUE THREAD

**Issue by gvenka008c** [gmr/consulate#88]
Hi,

I followed the below steps for backup / restore of Consul KV. After the restore Vault was throwing error as "\* failed to decode seal configuration: invalid character 'e' looking for beginning of value". Can you please suggest?

```
$ consulate --api-host <hostname> --api-port 8500 kv backup -b --file dump.json

$consulate --api-host  <hostname> --api-port 8500 kv restore --file dump.json

$ vault status
Error checking seal status: Error making API request.

URL: GET http://<hostname>:8200/v1/sys/seal-status
Code: 500. Errors:

* failed to decode seal configuration: invalid character 'e' looking for beginning of value
```

Thanks,
Govind

**Comment by vikas027** [comment]
Hey @gvenka008c ,

I think you missed `-b` in your restore command. I have just checked on Vault version 0.6.1 and Consul version 0.6.4. 

Cheers,
Vikas

**Comment by gmr** [comment]
Assuming this was the case since it's not been updated and there is the binary flag.
